### ISSUE TITLE
ChatGPT-4 (only) issue

### ISSUE THREAD

**Issue by andreabolandrina** [NicoleFaye/Chat-Gpt-Long-Text-Input#20]
Hi,

Thanks for the plugin.

I noticed it no longer pastes all parts when using chatgpt-4 but it still works with chatgpt-3.5.
Maybe chatgpt-4 is too slow at responding?

The result is that instead of the 4/5 parts that should get pasted I only get 2/3 successful ones.

Anyone else experiencing this issue?

Kind regards,
Andrea

**Comment by NicoleFaye** [comment]
I just tested it on firefox, i did initially get a message along the lines of "we have detected unusual activity please try again later"

But after creating a new chat and entering the messsage "test", I was later able to successfully input a messasge into a new gpt-4 session.

What browser are you using and do you have some sample input i can test with that isn't completing for you?

**Comment by andreabolandrina** [comment]
Firefox 114.0 on Linux

If the text is long enough (eg the transcript of a 20+ minute video) then I experience the problem.

I just experimented with this video: https://www.youtube.com/watch?v=G-TnrmZtaCw
Video transcript: [sample.txt](https://github.com/NicoleFaye/Chat-Gpt-Long-Text-Input/files/11739903/sample.txt)

With chatgpt-3.5 it gets correctly broken down in 5 messages, with chatgpt-4 in (normally) 2 messages only...

**Comment by NicoleFaye** [comment]
okay ill mess around with this and see what i come up with. thanks for letting me know.

**Comment by NicoleFaye** [comment]
I am able to reproduce the problem. I will start working on a fix today or tomorrow. You are probably right with the timing issue with gpt-4 being slower. Thanks again for pointing this out.

**Comment by NicoleFaye** [comment]
So I think I have narrowed down the issue.  I hit my limit testing solutions so I will continue on this later tonight when my limit is lifted.
![image](https://github.com/NicoleFaye/Chat-Gpt-Long-Text-Input/assets/41876584/46ca39e8-7481-46b3-86dc-d6d3f091e3b8)

**Comment by andreabolandrina** [comment]
When I found this plugin it was working perfectly.
Then OpenAI must have released an update that broke it completely.
Then you fixed it with the 3rd of June update and then (soon after) I started noticing the plugin failing to upload pieces of content... maybe due to another OpenAI update, not sure.

Anyway, thanks for supporting this! ;-)

**Comment by NicoleFaye** [comment]
I added a delay between messages because i think its sending messages before the website is prepared to take them. I was able to successfully get the full messages sent after this update. I will be updating the plugin store listings shortly. 

Whenever OpenAI changes their ui it can mess up the plugin. I try to keep on top of it but users bringing the issues to my attention is very helpful, so thank you. 

After pushing this fix I plan to add a setting to be able to manually adjust this delay as a user to be shorter or longer but i have no ETA for that yet.

In the meantime after this update you can browse to where the plugin is installed, and there will be a config.json file, in that file there will be an entry for "timeBetweenMessages" and you can edit it manually if the delay is not enough.
