### ISSUE TITLE
Trojan:Script/Sabsik.FL.B!ml

### ISSUE THREAD

**Issue by rafaelvectar** [NicoleFaye/Chat-Gpt-Long-Text-Input#23]
Windows Defender is indicating that Chrome-Main and Chrome-Dev have a virus (Trojan:Script/Sabsik.FL.B!ml).

**Comment by NicoleFaye** [comment]
Can you provide a screenshot? I am running windows 10 and have had no such popup. What version of windows are you on?

**Comment by rafaelvectar** [comment]
Yes of course Nicole. 
I'm using Windows 10 too. 

Take a look:
[Alert screenshot](https://i.postimg.cc/zBcRhQxR/1.jpg) 
[Trojan details](https://i.postimg.cc/fydjRZMb/2.jpg)
[My Windows Defender database version](https://i.postimg.cc/P55p6h08/image.png)

Link provided by Windows Defender:
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FSabsik.FL.B!ml&threatid=2147780207

**Comment by NicoleFaye** [comment]
This is actually pretty interesting. I realized I wasn't using windows defender because I use malwarebytes premium. Once I turned on windows defender I was able to somewhat reproduce it but its interesting because it is showing it as a different threat to me.
![image](https://github.com/NicoleFaye/Chat-Gpt-Long-Text-Input/assets/41876584/1e6813d2-c96e-48bf-bd51-43ed3628efc2)


I'm going to say this is a false positive on windows defenders side. I would say try using another antivirus and see what the results are. 

I ran the files and source urls through virustotal.com here are the results:

https://www.virustotal.com/gui/url/6277bbc579c237b5bcdb878b02792b2a003a4fbfff11abc9771dfd8dc1aa1d90?nocache=1
https://www.virustotal.com/gui/url/7b9bddf85d7ad27d803373a776e2ecbe46ff0b4ce3e86454f00c9b2cf7f66ecd?nocache=1
https://www.virustotal.com/gui/file/84c694c8c41f864d7d0710bdac04e920fb02019a8eccf1456e679075c960ecd3?nocache=1
https://www.virustotal.com/gui/file/0dede121e0bc885a520478ae61a4e43efb6ece9c8d7ed986d7e17710805ccbac/detection

I promise you there is nothing malicious in the code and its interesting how only the chrome branches are getting it. If you are still concerned you could always use the firefox version.
